USE [master]
GO

/****** Object:  Database [kullanicilar]    Script Date: 4.11.2019 11:19:37 ******/
CREATE DATABASE [kullanicilar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kullanicilar', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\kullanicilar.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'kullanicilar_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\kullanicilar_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kullanicilar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [kullanicilar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [kullanicilar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [kullanicilar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [kullanicilar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [kullanicilar] SET ARITHABORT OFF 
GO

ALTER DATABASE [kullanicilar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [kullanicilar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [kullanicilar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [kullanicilar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [kullanicilar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [kullanicilar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [kullanicilar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [kullanicilar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [kullanicilar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [kullanicilar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [kullanicilar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [kullanicilar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [kullanicilar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [kullanicilar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [kullanicilar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [kullanicilar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [kullanicilar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [kullanicilar] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [kullanicilar] SET  MULTI_USER 
GO

ALTER DATABASE [kullanicilar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [kullanicilar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [kullanicilar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [kullanicilar] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [kullanicilar] SET  READ_WRITE 
GO

